# Generated by Django 6.1.1 on 2026-09-27 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "slug",
                    models.CharField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Minuscules, chiffres et tirets ; ni au début ni à la fin.",
                                regex="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Actif"), ("suspended", "Suspendu")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "owner_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "owner_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("plan_key", models.CharField(blank=True, default="", max_length=80)),
                ("entitlement_revision", models.PositiveBigIntegerField(default=0)),
                (
                    "template_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "template_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=253, unique=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "hostname"],
            },
        ),
    ]
