# Generated by Django 6.1.1 on 2026-09-27 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("actor", models.CharField(max_length=120)),
                ("action", models.CharField(db_index=True, max_length=100)),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
