# Generated by Django 6.1.1 on 2026-09-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=120)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "key"), name="rbac_role_key_par_espace"
                    )
                ],
            },
        ),
    ]
