# Generated by Django 6.1.1 on 2026-09-27 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="accounts",
                to="rbac.role",
            ),
        ),
    ]
